from indexapp.settings import *

MIGRATION_MODULES = {
'auth': None,
'contenttypes': None,
'default': None,
'sessions': None,
"indexcorporateactionstatus":None,
"indexdailydividenddetail":None,
"calendar":None,
"indexuserpermission":None,
"indexconfiguration":None,
"indexsectorweights":None,
"indexindustryweights":None,
"currencypair":None,
"instrumentadtv":None,
"instrumentfreefloat":None,
"indexdailydividend":None,
"indexuniverse":None,
"gdp":None,
"indexfamily":None,
"instrumentquantitativefactor":None,
"requirements":None,
"lookuptables":None,
"sector":None,
"indextaxgroup":None,
"index":None,
"subsector":None,
"indexdivisor":None,
"corporateactiondividend":None,
"web_app":None,
"supersector":None,
"fxrate":None,
"indexanalytics":None,
"currency":None,
"indexvalue":None,
"indexsupersectorweights":None,
"taxrate":None,
"calendarholiday":None,
"indexdailymarketcap":None,
"corporateactionspinoff":None,
"industry":None,
"indexsubsectorweights":None,
"indexrebalancedate":None,
"rebalance":None,
"instrumentmarketcap":None,
"indexconstituent":None,
"permission":None,
"analytics":None,
"indexworkflow":None,
"corporateaction":None,
"utils":None,
"corporateactionstocksplit":None,
"corporateactionrightsissue":None,
"indexindustry":None,
"indexcalendar":None,
"indexcategory":None,
"country":None,
"instrumentprice":None,
"exchange":None,
"instrument":None,
"taxgroup":None,
"source":None,
"status":None,
"indextype":None,
"corporateactiontype":None,
"divisortype":None,
"fixingtype":None,
"instrumenttype":None,
"dividendtype":None,
"calendartype":None,
}