# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-30 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=3)),
                ('description', models.CharField(max_length=50)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime')),
                ('modifyuserid', models.ForeignKey(blank=True, db_column='ModifyUserid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'currency',
                'managed': True,
            },
        ),
    ]
